@startuml
'https://plantuml.com/sequence-diagram

box Domain1 #White
participant Domain1
database "Anchor\nReference" as Domain1DB
end box

box Domain2
participant Domain2
database "Anchor\nReference" as Domain2DB
queue "orb.anchor" as anchor_2
end box

box Domain3 #White
participant Domain3
queue "orb.anchor" as anchor_3
end box

activate Domain1
Domain1 -> Domain2: Post(Create)
note over Domain1
Post Create (containing
an anchor linkset) to
servers in followers list.
end note

activate Domain2
Domain2 -> Domain2: Authenticate Domain1\nusing HTTP signature
Domain2 --> Domain1: OK

deactivate Domain1

Domain2 -> Domain2: Extract anchor linkset\nfrom Create activity\nand store to CAS

Domain2 -> anchor_2: Publish(anchorInfo)

note over anchor_2
The hashlink of the anchor
linkset is posted to
the anchor queue to be
processed by the Observer.
end note

activate anchor_2

anchor_2 --> Domain2: OK

Domain2 -> Domain3: Post(Announce)

activate Domain3

Domain3 -> Domain3: Authenticate Domain2\nusing HTTP signature
Domain3 --> Domain2: OK

deactivate Domain2

Domain3 -> Domain3: Extract anchor linkset\nfrom Announce activity\nand store to CAS

Domain3 -> anchor_3: Publish(anchorInfo)

activate anchor_3

note over anchor_3
The hashlink of the anchor
linkset is posted to
the anchor queue to be
processed by the Observer.
end note
anchor_3 --> Domain3: OK

deactivate Domain3

anchor_2 -> Domain2: anchorInfo

activate Domain2

note over Domain2
The anchor linkset is retrieved
from CAS using the hashlink in
the anchorInfo and the anchor
linkset is processed by the
Observer.
end note

Domain2 -> Domain1: Like activity

activate Domain1
Domain1 -> Domain1: Authenticate Domain2\nusing HTTP signature
Domain1 --> Domain2: OK

Domain2 --> anchor_2: ACK

deactivate anchor_2

deactivate Domain2

Domain1 -> Domain1DB: Add Domain2 to\nanchor reference DB
activate Domain1DB
Domain1DB --> Domain1: OK
deactivate Domain1DB
deactivate Domain1

anchor_3 -> Domain3: anchorInfo

activate Domain3

note over Domain3
The anchor linkset is retrieved
from CAS using the hashlink in
the anchorInfo and the anchor
linkset is processed by the
Observer.
end note

Domain3 -> Domain2: Like activity

activate Domain2

Domain2 -> Domain2: Authenticate Domain3\nusing HTTP signature
Domain2 --> Domain3: OK

Domain3 --> anchor_3: ACK

deactivate anchor_3

Domain2 -> Domain2DB: Add Domain3 to\nanchor reference DB
activate Domain2DB
Domain2DB --> Domain2: OK
deactivate Domain2DB
deactivate Domain2

Domain3 -> Domain1: Like activity

activate Domain1
Domain1 -> Domain1: Authenticate Domain3\nusing HTTP signature
Domain1 --> Domain3: OK

deactivate Domain3

Domain1 -> Domain1DB: Add Domain3\nto anchor reference DB
activate Domain1DB
Domain1DB --> Domain1: OK
deactivate Domain1DB
deactivate Domain1

@enduml
