@startuml
'https://plantuml.com/sequence-diagram

box Domain1 #White
participant Domain1
queue anchor_event
database Domain1DB
end box

box Domain2
participant Domain2
database Domain2DB
queue anchor_2
end box

box Domain3 #White
participant Domain3
database Domain3_db
queue anchor_3
end box

activate anchor_event
anchor_event -> Domain1: AnchorEvent message

activate Domain1
Domain1 -> Domain1: Batch Writer\nprocesses\nAnchorEvent
Domain1 -> Domain2: Create activity
note over Domain1
Post Create
to servers in
followers list.
end note

activate Domain2
Domain2 -> Domain2: Authenticate Domain1\nusing HTTP signature
Domain2 --> Domain1: OK

Domain1 --> anchor_event:ACK

deactivate anchor_event

deactivate Domain1

Domain2 -> anchor_2: AnchorEvent

activate anchor_2

anchor_2 --> Domain2: ACK

note left
The AnchorEvent in
the Create activity
is posted to the
anchor queue to be
processed by the
Observer.
end note

Domain2 -> Domain3: Announce activity

activate Domain3

Domain3 -> Domain3: Authenticate Domain2\nusing HTTP signature
Domain3 --> Domain2: OK

deactivate Domain2

Domain3 -> anchor_3: AnchorEvent

activate anchor_3
anchor_3 --> Domain3: ACK

deactivate Domain3

note left
The AnchorEvent in
the Announce activity
is posted to the anchor
queue to be processed by
the Observer.
end note

anchor_2 -> Domain2: AnchorEvent

note left
The AnchorEvent is
processed by the
Observer.
end note

activate Domain2

Domain2 --> anchor_2: ACK

deactivate anchor_2

Domain2 -> Domain1: Like activity

activate Domain1
Domain1 -> Domain1: Authenticate Domain2\nusing HTTP signature
Domain1 --> Domain2: OK

deactivate Domain2

Domain1 -> Domain1DB: Add Domain2 to\nanchor links DB
deactivate Domain1

anchor_3 -> Domain3: AnchorEvent

activate Domain3

note left
The AnchorEvent is
processed by the
Observer.
end note

Domain3 --> anchor_3: ACK

deactivate anchor_3

Domain3 -> Domain2: Like activity

activate Domain2

Domain2 -> Domain2: Authenticate Domain3\nusing HTTP signature
Domain2 --> Domain3: OK

Domain2 -> Domain2DB: Add Domain3 to\nanchor links DB

deactivate Domain2

Domain3 -> Domain1: Like activity

activate Domain1
Domain1 -> Domain1: Authenticate Domain3\nusing HTTP signature
Domain1 --> Domain3: OK

deactivate Domain3

Domain1 -> Domain1DB: Add Domain3\nto anchor links DB
deactivate Domain1

@enduml
