@startuml
'https://plantuml.com/component-diagram

skinparam linetype polyline

frame "Domain1" {
  database "AWS\nDocumentDB\nor MongoDB" as orbdb

  component "IPFS" as ipfs
  component Orb as orb1

  orb1 --> orbdb

  interface "HTTPS" as rest1

  orb1 -left- rest1

  component "AMQP\nRabbitMQ" as amqp
  component "AWS KMS" as aws_kms
  component "Aries Web KMS" as aries_kms

  orb1 ..> aws_kms
  orb1 ..> aries_kms
  orb1 ---> amqp

  aries_kms --> orbdb

  orb1 .> ipfs

  frame "VCT" {
    component "VCT" as vct
    component "VCT Log\nGoogle Trillian" as vct_log

    component "VCT Signer\nGoogle Trillian" as vct_signer

    database "PostgreSQL\nor MySQL" as vctdb

    interface "HTTPS" as vct_rest
    vct -left- vct_rest

    vct --> vct_log
    vct -> vct_signer
    vct -> vctdb
    vct_log --> vctdb
    vct_signer --> vctdb
  }

  orb1 --> vct_rest
}

frame "Domain2" as domain2 #Azure

interface "HTTPS" as rest2 #Azure

domain2 -left- rest2

frame Domain3 as domain3 #Azure

interface "HTTPS" as rest3 #Azure

domain3 -left- rest3

orb1 ---> rest2
domain2 --> rest1
domain2 --> rest3

domain3 -> vct_rest

@enduml